version: "2.4"

services:
  webshop:
    build:
      context: ../webshopApp
      dockerfile: ./Dockerfile
    ports:
      - "8888:8080"
    links: 
      - zuul
  oauthserver:
    build:
      context: ../oauthserver
      dockerfile: ./Dockerfile
    ports:
      - "8300:8300"
  eureka:
    build: ../eureka_server
    ports:
      - 8761:8761
    environment:
      - JVM_OPTS=
        -DEUREKA_SERVER=http://localhost:8761/eureka
    mem_limit: 800m
    mem_reservation: 600m
  zuul:
    build: .
    ports:
      - 8084:8084
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    links:
      - eureka
    depends_on:
      - eureka
    mem_limit: 800m
    mem_reservation: 600m
  hystrixturbine:
    build: ../hystrix_turbine
    ports:
      - 8099:8099
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    links:
      - eureka
      - zuul
      - coreuser
      - corerole
      - corecategory
      - coreproduct
      - compproductcategory
      - compuserrole
      - apicategory
      - apiproduct
      - apirole
      - apiuser
    depends_on:
      - eureka
      - zuul
    mem_limit: 800m
    mem_reservation: 600m
  coreuser:
    build: ../usercore
    ports:
      - 8101:8101
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    links:
      - eureka
      - oauthserver
    depends_on:
      - eureka
      - zuul
    mem_limit: 800m
    mem_reservation: 600m
  corerole:
    build: ../rolecore
    ports:
      - 8100:8100
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    links:
      - eureka
      - oauthserver
    depends_on:
      - eureka
      - zuul
    mem_limit: 800m
    mem_reservation: 600m
  coreproduct:
    build: ../productcore
    ports:
      - 8201:8201
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    links:
      - eureka
      - oauthserver
    depends_on:
      - eureka
      - zuul
    mem_limit: 800m
    mem_reservation: 600m
  corecategory:
    build: ../categorycore
    ports:
      - 8200:8200
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    links:
      - eureka
      - oauthserver
    depends_on:
      - eureka
      - zuul
    mem_limit: 800m
    mem_reservation: 600m
  compuserrole:
    build: ../comp_user_role
    ports:
      - 8102:8102
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    links:
      - eureka
      - oauthserver
    depends_on:
      - eureka
      - zuul
    mem_limit: 800m
    mem_reservation: 600m
  compproductcategory:
    build: ../comp_category_product
    ports:
      - 8202:8202
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    links:
      - eureka
      - oauthserver
    depends_on:
      - eureka
      - zuul
    mem_limit: 800m
    mem_reservation: 600m
  apiuser:
    build: ../api_user
    ports:
      - 8103:8103
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    links:
      - eureka
      - oauthserver
    depends_on:
      - eureka
      - zuul
    mem_limit: 800m
    mem_reservation: 600m
  apirole:
    build: ../api_role
    ports:
      - 8104:8104
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    links:
      - eureka
      - oauthserver
    depends_on:
      - eureka
      - zuul
    mem_limit: 800m
    mem_reservation: 600m
  apiproduct:
    build: ../api_product
    ports:
      - 8203:8203
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    links:
      - eureka
      - oauthserver
    depends_on:
      - eureka
      - zuul
    mem_limit: 800m
    mem_reservation: 600m
  apicategory:
    build: ../api_category
    ports:
      - 8204:8204
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    links:
      - eureka
      - oauthserver
    depends_on:
      - eureka
      - zuul
    mem_limit: 800m
    mem_reservation: 600m