version: '2.4'

services:
  webshop:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - 8088:8080
    environment:
      - JVM_OPTS=
        -DEUREKA_SERVER=http://localhost:8090/eureka
    mem_limit: 600m
    mem_reservation: 500m

#services:
#  legacywebshop:
#    image: mavogel/hska-vis-legacywebshop
#    ports:
#      - "8888:8080"
#    networks:
#      local_dev_net:
#          aliases:
#              - legacywebshop

#networks:
#  local_dev_net:
#    driver: bridge
