spring:
  application:
    name: zuul
  cloud:
    config:
      enabled: false
server:
  port: 8084
eureka:
    client:
        serviceUrl:
            #defaultZone: http://Eureka:8761/eureka/
            defaultZone: http://localhost:8761/eureka/
        instance:
            preferIpAdress: true
            leaseRenewalIntervallInSeconds: 5
            metadataMap:
                instanceId: "${spring.application.name}:${random.value}"
zuul:
  ignoredServices: '*'
  routes:
    catalogue: /catalogue/**
    category: /category/**
    product: /product/**
    products: /products/**
    users: /users/**